### ISSUE TITLE
Imported Condition Lab JSON missing Active Effect Config

### ISSUE THREAD

**Issue by MalakanC** [death-save/combat-utility-belt#475] opened 2021-02-09 01:22 UTC
**Describe the bug**
Created a Condition Lab setup with Active Effects and Triggers on many of the items.

The Export displays these Active Effects in the JSON file. Upon importing the JSON into a new world, the Active Effects have not been brought into the Condition Lab

**To Reproduce**
Import an exported JSON file from a previous setup that includes Active Effect configurations after restoring the defaults

**Expected behavior**
The data is exported, should be imported too. Lest I now have to go through each Active Effect and re-apply again for each world I wish to use it with.

**Screenshots**

**Environment Info (please complete the following information):**
 - Foundry Version: 0.7.9
 - Game System / Version: dnd5e 1.2.4
 - CUB Version 1.4
 - Browser Chrome
 - OS Windows 10

**Additional context**
The JSON file was too large to upload whole, seems to have a significant amount of compendium entries repeated for each condition.

Here is a pastebin of one condition from the JSON which includes an Active Effect.
https://pastebin.com/sYFzuj1i

**Comment by eclarke12** [comment] 2021-02-09 03:34
Duplicate of #429

**Closed by eclarke12** 2021-02-09 03:34 UTC
Labels: bug, duplicate, unverified
