### ISSUE TITLE
NOT AN ISSUE! I have a Concentrator Idea

### ISSUE THREAD

**Issue by paulcheeba** [death-save/combat-utility-belt#463] opened 2021-01-17 02:54 UTC
I was playing around with the remove DAE macro:
```
//type the name of the effect in "EFFECT NAME"

let dae_effect = async function() {

const effect_name = "EFFECT NAME"; //<-- change to "Concentrating"

const effect = token.actor.effects.entries;

for (let i = 0; i < effect.length; i++){

let condition = effect[i].data.label;

let status = effect[i].data.disabled;

let effect_id = effect[i].data._id;

if ((condition === effect_name) && (status === false)) {

await token.actor.updateEmbeddedEntity("ActiveEffect", {"_id": effect_id, "disabled" : true});

}

if ((condition === effect_name) && (status === true)){

await token.actor.updateEmbeddedEntity("ActiveEffect", {"_id": effect_id, "disabled" : false});

}

}

}

dae_effect();
```

Perhaps you can implement this into your code so when a token fails its con save, this built in macro removes the Concentrating DAE and subsequently its status marker.

**Comment by eclarke12** [comment] 2021-01-20 04:30
Any functionality to remove Concentrating will currently come from within CUB instead of leveraging external modules. Marking as a duplicate of #451

**Closed by eclarke12** 2021-01-20 04:30 UTC
Labels: duplicate
