### ISSUE TITLE
Condition Lab export missing Active Effects

### ISSUE THREAD

**Issue by Silzin** [death-save/combat-utility-belt#500] opened 2021-03-25 18:40 UTC
Hello,

I am really appreciating all of the hard work you have put into these tools.  i seem to be having a bug with the import and export of the Conditions.  i have exported 4 or 5 times the same conditions list and each time its a different size.  some times its around 300 kb, other times its around 30kb.  Either way when I go to import to the other Foundry world, not the same computer its not importing the effects.  some times its getting the names of the conditions and the images, but not the effects.  

Thank you, Eric

**Comment by ctbritt** [comment] 2021-03-27 17:41
Having the same issue. Importing a json file doesn't bring in the active effects that i can see in the json file.

**Comment by uLotUu** [comment] 2021-03-29 14:33
Same here

**Comment by eclarke12** [comment] 2021-03-29 14:53
Seems like a duplicate of #429

**Closed** 2021-05-29 23:54 UTC
Labels: bug, duplicate, unverified
