### ISSUE TITLE
[PF1] CUB hides custom buffs icons from token for Status Icon Counter

### ISSUE THREAD

**Issue by ManaHime** [death-save/combat-utility-belt#503] opened 2021-03-28 14:47 UTC
**Describe the bug**
With everything updated (and current Foundry stable)
In PF1e when creating a custom buff on an actor and displaying it on the token, it is not shown in the icon menu that can be used by Status Icon Counter when CUB is enabled on the world. I disabled every option except for XP after the end of a combat, but it still hides the custom buff

**To Reproduce**
1. Create an actor (for example a Player Character)
2. Drop the token on a scene and go on the character sheet, go in Buff and create a custom buff, then enable it.
3. It will show on the token as a small icon.
4. Right click the token and click on the status icon menu thingy.
5. See error

**Expected behavior**
Normally the custom icon should show at the bottom of that status icon menu so that it could be clicked to increase the counter with Status Icon Counter, however this is not the case with CUB enabled

**Environment Info (please complete the following information):**
 - Foundry Version: 0.7.9
 - Game System / Version: pf1e 0.77.19
 - CUB Version 1.4.0
 - Status Icon Counter 2.0.3
 - Browser Chrome
 - OS Windows

**Comment by websterguy** [comment] 2021-05-08 01:35
Looks like the TokenUtility class overwrites the token hud status effect choices without respecting the enhanced conditions settings. And I think since pf1e doesn't use "effects" to store its buffs, they don't get added to the window.

**Comment by eclarke12** [comment] 2022-02-02 06:17
duplicate of #490

**Closed by eclarke12** 2022-02-02 06:17 UTC
Labels: bug, unverified
