### ISSUE TITLE
Update post of a token in the chat when a condition is removed

### ISSUE THREAD

**Issue by apoapostolov** [death-save/combat-utility-belt#114] opened 2020-04-13 11:22 UTC
Currently, when a token loses a condition, the chat post of that token is not updated. This is confusing as many players rely on these posts to recognize the condition of a token among many opponents. 

It would be great if the chat post format is changed a bit:
- Under the token name there's a bold statement that says: **TOKENNAME is (no longer) CONDITIONNAME.** that refers only to the changed condition. 
- Then below it is a list of the current conditions (if any) that the token has.

**Comment by eclarke12** [comment] 2020-04-29 05:20
duplicate of #40

**Closed by eclarke12** 2020-04-29 05:20 UTC
