### ISSUE TITLE
[Hide Names] Names not hidden when automatically rolling a save through MidiQOL

### ISSUE THREAD

**Issue by GhostwheelX** [death-save/combat-utility-belt#626] opened 2021-12-03 08:20 UTC
When you have enemies roll a saving throw to chat automatically through MidiQOL, their names are revealed even if they are hidden everywhere else. Is there a way to fix that by any chance?

**Comment by eclarke12** [comment] 2021-12-03 15:29
duplicate of #582

**Closed by eclarke12** 2021-12-03 15:29 UTC
Labels: bug, duplicate, unverified
