### ISSUE TITLE
Attempting to set custom overlay condition results in non-overlay instead

### ISSUE THREAD

**Issue by apoapostolov** [death-save/combat-utility-belt#302] opened 2020-10-24 23:59 UTC
Latest CUB. D&D5E. I am using a triggered condition to set a creature to a custom condition Dead. It works, except it doesn't respect the overlay option and instead adds a small icon. 

![image](https://user-images.githubusercontent.com/4083812/97095863-b642a780-166d-11eb-8049-4f7e1e5579a5.png)

![image](https://user-images.githubusercontent.com/4083812/97095869-c490c380-166d-11eb-8452-44feadd7ccbd.png)

**Comment by eclarke12** [comment] 2020-10-25 04:07
duplicate of #295

**Closed by eclarke12** 2020-10-25 04:07 UTC
Labels: bug
