### ISSUE TITLE
Concentrator ignores temporary HP damage

### ISSUE THREAD

**Issue by mrendleman** [death-save/combat-utility-belt#695] opened 2022-07-19 23:34 UTC
**Describe the bug**
Damage that only affects temp HP doesn't trigger a Concentration save. Additionally, when damage taken wipes out temp HP and some normal HP, the Con save DC is calculated only using the damage that affects the real hit points.

**To Reproduce**
- Give a concentrating token 5 temp HP
- Apply 5 damage (I'm doing this by right-clicking the token and decreasing the health value by 5)
- Concentrator then doesn't ask the player if they'd like to make a Con save

**Environment Info (please complete the following information):**
 - Foundry Version: 9, build 269
 - Game System / Version: dnd5e 1.5.6
 - CUB Version: 1.9.2
 - Browser: Chrome
 - OS: Windows 10

**Additional info**
My guess is that this could be fixed by considering temp HP when making calls to `_wasDamageTaken()` and  `_calculateDamage()` within `_onPreUpdateToken()` and/or `_onPreUpdateActor()` in `concentrator.js`.

**Comment by eclarke12** [comment] 2022-07-27 04:37
Duplicate of #117

**Closed** 2022-07-28 05:05 UTC
Labels: bug
