### ISSUE TITLE
Error: Canvas drawing failed for the TokenLayer, see the console for more details.

### ISSUE THREAD

**Issue by M0nk3yy** [death-save/combat-utility-belt#179] opened 2020-05-30 18:32 UTC
No error on GM end. Play logs in and gets a notification of the error: Canvas drawing failed for the TokenLayer, see the console for more details.

Error occurs with no other mods active. Console screenshot:

![image](https://user-images.githubusercontent.com/66137312/83336518-0890bf80-a2ac-11ea-892f-f9f453f6b811.png)

- Foundry Version: 0.6.0
- CUB Version 1.1
- Browser Chrome
- OS Windows 10

**Comment by eclarke12** [comment] 2020-06-05 19:57
@M0nk3yy can you confirm this is fixed? I think it was resolved in FVTT 061

**Comment by M0nk3yy** [comment] 2020-06-06 20:11
Just updated to FVTT 061 and the error persists.

**Comment by eclarke12** [comment] 2020-06-11 04:15
@M0nk3yy is this happening to a single player or multiple players? Can you please DM me (here or on discord) the world in question and name of the affected player/s so I can investigate further?

**Comment by M0nk3yy** [comment] 2020-06-15 17:39
Currently using FVTT 062, dnd5e 0.92.

Error only occurs in Chrome - doesn't occur when logging in through Foundry, Opera, or Edge. Doesn't occur when using Chrome on another machine.

Error persists with all Chrome extensions disabled.

**Comment by eclarke12** [comment] 2020-06-30 04:51
@M0nk3yy I still can't reproduce this. Can you please do the following for me:
1. Check for Chrome updates and report back (include the Chrome version)
2. Send the full console log by right-clicking in the console and choosing save-as then send it as a private message here or on discord
3. Clear cookies and cache

**Comment by M0nk3yy** [comment] 2020-08-29 15:07
Hadn't tested in a while. Doesn't appear to still be happening for me.

**Closed** 2020-08-29 15:06 UTC
Labels: bug, non-repro
