### ISSUE TITLE
Trusted Players receiving permission error

### ISSUE THREAD

**Issue by apoapostolov** [death-save/combat-utility-belt#191] opened 2020-06-07 13:58 UTC
0.6.2, latest CUB. Trusted player is seeing the following error:

![image](https://user-images.githubusercontent.com/4083812/83970758-1bc11200-a8e0-11ea-8ee9-2c77071775c6.png)

Is there anything I can do to stop these errors, what feature is causing it?

**Comment by eclarke12** [comment] 2020-06-07 15:02
This is a regression caused by some changes to provide compatibility with PF2e. It shouldn't cause any issues for the player (other than the error)

**Comment by eclarke12** [comment] 2020-06-07 15:03
Duplicate of #189

**Closed by eclarke12** 2020-06-07 15:03 UTC
Labels: bug
