### ISSUE TITLE
Triggler macro calls pass the token/actor instance that called the trigger

### ISSUE THREAD

**Issue by kandashi** [death-save/combat-utility-belt#471] opened 2021-02-03 21:55 UTC
Referencing Discord chat from 03/02/2121

Kandashi (He/Him)Today at 9:47 PM
Ive got a quick question about the triggler triggered macros, is there any way to identify which token triggered the macro? or could that be added in?
Evan (errational) [UTC+7]Today at 9:48 PM
someone else mentioned that recently and there's an issue for it, but i don't know how high up the priority list it is tbh
Kandashi (He/Him)Today at 9:48 PM
no problem, just wanted to check I wasnt missing something
Evan (errational) [UTC+7]Today at 9:48 PM
it was a pretty obvious miss in the functionality to not pass it through
Kandashi (He/Him)Today at 9:49 PM
i might have a poke around and see if I can get a MR or something
Evan (errational) [UTC+7]Today at 9:50 PM
i have CUB on the operating table this week, so i can probably take a look. if you want to help you can add the issue to the v1.3.9 milestone and drop a comment in there mentioning this chat

**Comment by kandashi** [comment] 2021-02-03 22:00
I believe here: https://github.com/death-save/combat-utility-belt/blob/2210e579090fb863cb65dff7124ca4f03d1880e3/modules/triggler/triggler.js#L51
you can probably add a check for furnace passing arguments, then pass the entity.id or somesuch

**Comment by eclarke12** [comment] 2021-02-03 22:09
duplicate of #453

**Closed by eclarke12** 2021-02-03 22:09 UTC
Labels: duplicate
