### ISSUE TITLE
Encumbrance as an attribute in Triggler

### ISSUE THREAD

**Issue by DFreds** [death-save/combat-utility-belt#464] opened 2021-01-18 03:24 UTC
**Is your feature request related to a problem? Please describe.**
I would like to support [variant encumbrance](https://5thsrd.org/rules/abilities/strength/#variant-encumbrance) via conditions. Currently, I have no way to trigger a condition based on encumbrance.

**Describe the solution you'd like**
An attribute added to Triggler for encumbrance.

**Describe alternatives you've considered**
Manually applying conditions that include the effects I want

**Comment by eclarke12** [comment] 2021-02-04 21:00
Duplicate of #364

**Closed by eclarke12** 2021-02-04 21:00 UTC
Labels: duplicate, enhancement, 🔫t
