### ISSUE TITLE
Player report of message about permission to update

### ISSUE THREAD

**Issue by Jonwh25** [death-save/combat-utility-belt#189] opened 2020-06-06 19:04 UTC
**Describe the bug**
My player got a strange popup on them when they lost connection and reconnected.  It said

User (his name) lacks permissions to update the World setting combat-utility-belt-.coreStatusIcons

**To Reproduce**
1. player disconnects 
2. player reconnects

or if I enable/disable any module and it refreshes.

**Expected behavior**
NA

**Screenshots**

**Environment Info (please complete the following information):**
 - Foundry Version: 0.6.0
 - CUB Version 1.1.1
 - Browser Firefox
- OS Win10

**Additional context**

**Comment by schultzcole** [comment] 2020-06-06 19:48
I can reproduce this issue in chrome. Foundry 0.6.0, CUB 1.1.1

**Comment by eclarke12** [comment] 2020-06-07 15:03
This is a regression caused during the last update. Will be fixed for v1.1.2

**Comment by tposney** [comment] 2020-06-12 01:50
I noticed this as well. The problem seems to be enhanced-conditions.js
```
    static _backupCoreIcons() {
        CONFIG.defaultStatusEffects = CONFIG.defaultStatusEffects || duplicate(CONFIG.statusEffects);
        if (!Object.isFrozen(CONFIG.defaultStatusEffects)) {
            Object.freeze(CONFIG.defaultStatusEffects);
        }
          Sidekick.setSetting(BUTLER.SETTING_KEYS.enhancedConditions.coreIcons, CONFIG.defaultStatusEffects);
    }
```
If I change it to 
```
if (game.user.isGM)   Sidekick.setSetting(BUTLER.SETTING_KEYS.enhancedConditions.coreIcons, 
```
The problem goes away

**Comment by eclarke12** [comment] 2020-06-12 04:41
This is fixed in the next patch

**Comment by apoapostolov** [comment] 2020-06-13 10:14
Glad to hear it, my players repost the same thing at each login, not just reconnection.

**Closed** 2020-06-19 20:39 UTC
Labels: bug
