### ISSUE TITLE
Trigger enhancement: Add attributes.inspiration support

### ISSUE THREAD

**Issue by bcartwright** [death-save/combat-utility-belt#468] opened 2021-01-27 21:37 UTC
**Is your feature request related to a problem? Please describe.**
While playing 5e, I would like the Inspiration resource to be visually represented accurately on both the actor's token and character sheet. I wanted to use triggler to add a "Inspiration" condition whenever attributes.inspiration == true, but only a handful of values are visible to triggler. This could be a visual condition only, just like the example Bloodied (<50% hp) condition.

**Describe the solution you'd like**
Adding attributes.inspiration to the list of supported values would probably be the easiest change that would make this possible.

**Describe alternatives you've considered**
Other changes to CUB that would fix this include adding a text box to enter values, or including everything visible to token resource bars in the value selection drop-down menu.

Other solutions to my problem that don't involve changes to CUB include setting up macros to add or remove attributes.inspiration and an Inspiration condition at the same time. This is harder to use for players and GM than toggling inspiration from the sheet or token HUD utilities. It's also beyond my technical prowess, as my attempts at this have resulted in race conditions where the attributes.inspiration is not always updated. 

**Additional context**
![image](https://user-images.githubusercontent.com/16912450/106052910-041ce080-609f-11eb-9a25-378a5206c4e2.png)
So close!  

Current versions:  
CUB: 1.38  
Foundry: 0.7.9  
DnD5e: 1.2.2

**Comment by eclarke12** [comment] 2021-02-02 04:36
Duplicate of #149

**Closed by eclarke12** 2021-02-02 04:36 UTC
Labels: duplicate, enhancement, 🔫t
