### ISSUE TITLE
Custom Mapped Conditions Disappear Every Login Despite Saving the Mapping.

### ISSUE THREAD

**Issue by rtschaefer** [death-save/combat-utility-belt#672] opened 2022-04-03 05:44 UTC
**Describe the bug**
every time I log back into Foundry VTT, all of my enhanced conditions disappear, and the one and only condition available to apply to a token is the Blindness condition.  I constantly save my mapping, and this happens every single time I log back into my game (I use the Forge to host Foundry VTT). This is an enormous pain because all of the custom effects and triggler settings disappear when the conditions are eliminated from my saved custom mapping. 

**To Reproduce**
Log out of the game, then log back in.  

**Expected behavior**
Saved mapping does what it is supposed to do, and save my customized enhanced conditions. 

**Environment Info (please complete the following information):**
 - Foundry Version:  9
 - Game System / Version:  dnd5e (I assume the latest version?)
 - CUB Version 1.8.4
 - Browser: Chrome
 - OS: Windows 11

**Additional context**

One other strange thing happened not too long ago. At some point, even when the module retained my custom conditions, it wiped all of the custom effects (disadvantage on rolls; movement changes, etc.).  

I rely a lot on CUB as a DM, and this is really troubling for me to figure out. I dont even think "Find the Culprit" module would be feasible, because testing would require constantly logging back off and in again.

**Comment by eclarke12** [comment] 2022-04-03 20:23
Does this occur when only CUB is enabled?
Can you please provide some screenshots?

thanks!

**Comment by rtschaefer** [comment] 2022-04-07 23:52
Here is what happens, and this worked perfectly until the last few weeks!

(1) I create an Enhanced Condition and Save Mapping
![Custom Condition was added and saved](https://user-images.githubusercontent.com/95512317/162336664-e2ffcbee-e5cb-4280-b172-527659c471af.png)

(2) Create dice effects to happen on conditions and Save Mapping
![Condition effects created](https://user-images.githubusercontent.com/95512317/162337166-2056738d-5f5e-48b7-9b1b-359f452ab615.png)

(3) Log back into Foundry later on, only to discover
(A) Custom Condition Disappears

![Custom Condition disappears](https://user-images.githubusercontent.com/95512317/162337319-9f4bd18a-23d5-4cb1-a323-f372f75daad1.png)

(B) Custom effects are stripped!

![Custom Effects Eliminated](https://user-images.githubusercontent.com/95512317/162337361-10b3d1ec-bfa4-4b76-8bf2-445e84af8875.png)

(C) All Conditions Other than "Blinded" are Removed from Token Options 

![Only blinded sticks](https://user-images.githubusercontent.com/95512317/162337411-dcafdb1d-68d0-4985-93d4-8a9a355eaaea.png)

**Comment by rtschaefer** [comment] 2022-04-07 23:55
I have not tested when "only" CUB is enabled.  I can give it a try, although I will need to carefully document all of my active modules first, because there is no way I will remember them all perfectly when it comes time to add them back.

**Comment by rtschaefer** [comment] 2022-04-08 00:18
Ok, so I went ahead and turned off all modules except for CUB and not surprising, this problem does not occur at all. My custom conditions were intact (with their custom effects and triggler settings per normal), and the token conditions are correct. I cannot tell you how many hours went into customizing the effects on all of the enhanced conditions, but it was many hours indeed!

It would take me all weekend to use Find the Culprit! to identify potential conflicts, and of course there could be more than just one.  

Here are my active modules! If there is a module (or perhaps several) on the list that you already know routinely conflict with CUB, please let me know which ones to prioritize for an iterative test.  That said, most of what I use are modules that a lot of DMs are using, so it is probably something to prioritize for a fix.   
  
Active Modules:
----------
About Time 
Ace library 
Active Token Effects 
Advanced Macros 
Alternative Pause Icon 
Ambient Doors 
Autocomplete Inline Properties 
Automated Animations 
Automatic Journal Icon Numbers 
Backgroundless Pins 
Background Volume 
Baileywiki Maps Premium 
Better Rolls for 5e 
Better Roll Tables 
Better Roofs 
Beyond20 companion module 
Changelogs & Conflicts 
Character Actions List dnd5e 
Combat Utility Belt 
Compendium Browser 
Compendium Folders 
Cursor Hider 
Custom Nameplates 
Danger Zone 
D&D Beyond Importer 
DFreds Convenient Effects 
DFreds Droppables 
DFreds Effects Panel 
Dice So Nice! 
Dice Tray 
Dynamic effects using Active Effects 
Easy Ruler Scale 
Easy Target 
Enhanced Terrain Layer 
Entice with Dice so Nice 
Find the culprit 
Forien's Quest Log 
Forien's Unidentified Items 
Foundry Community Macros 
Foundry Community Tables 
FXMaster 
GM Screen 
Health Estimate 
Hey, Wait! 
Item Macro 
JB2A - Patreon Complete Collection 
Laptop Form Fix 
Less Fog 
Let Me Roll That For You! 
Levels 
lib - Color Settings 
Lib: Document Sheet Registrar 
Library: Scene Packer 
libWrapper
LiveKit AVClient 
Lock View 
LootsheetNPC5e 
Magic Items 
Michael Ghelfi Studios Audio Pack 
Midi QOL 
Monk's Active Tile Triggers 
Monk's Enhanced Journal 
Monk's Hotbar Expansion 
Monk's Little Details 
Monk's Scene Navigation 
Monk's TokenBar 
Multilevel Tokens 
Not Enough NPCs: A 5e NPC Generator 
Parallaxia 
Perfect Vision 
Permission Viewer 
PnP - Pointer and Pings! 
Polyglot 
PopOut! 
Popout Resizer 
Quick Encounters 
QuickScale 
Scene Transitions 
Search Anywhere 
Sequencer 
Settings Extender 
Simple Calendar 
Simplefog - Manual Fog of War 
SmallTime 
Smart Target 
socketlib 
SoundBoard by Blitz 
Storyteller 
Tabletop RPG Music 
Tagger 
Tasha’s Cauldron of Everything 
The Forge: More Awesomeness 
The Rollsmith - Dragon Saphira Dice Set 
Tidy5e Sheet 
Tidy UI - Game Settings 
Times Up 
Token Action HUD 
Token Attacher 
Token Auras 
Tokenizer 
Token Magic FX 
Token Mold 
Trigger Happy 
VTTA Core 
VTTA D&D Beyond Integration 
VTTA Tokens 
Wall Height 
Your Tokens Visible

**Comment by eclarke12** [comment] 2022-04-08 16:29
I would focus on the following mods: 
DFreds Convenient Effects
Dynamic effects using Active Effects
Monk's Little Details
Monk's TokenBar

Start by disabling those one at a time and see if the issue is resolved.

**Comment by rtschaefer** [comment] 2022-04-08 19:49
And the answer is.... DFred's Convenient Effects.  That module is so valuable to how I run my game, until the conflict is resolved, I will just have to live without customized token conditions on CUB.    Thanks for helping me through this! 

Side Note.
There are other issues I noticed in the last campaign, like Concentration statuses stacking instead of being replaced (I use Midi_Qol workflow for concentration and have it turned off for CUB, so I am not sure what is causing that one).  It can be daunting to try and isolate which module is doing what, and also when.

**Comment by eclarke12** [comment] 2022-07-28 03:19
> And the answer is.... DFred's Convenient Effects. That module is so valuable to how I run my game, until the conflict is resolved, I will just have to live without customized token conditions on CUB. Thanks for helping me through this!
> 
> Side Note. There are other issues I noticed in the last campaign, like Concentration statuses stacking instead of being replaced (I use Midi_Qol workflow for concentration and have it turned off for CUB, so I am not sure what is causing that one). It can be daunting to try and isolate which module is doing what, and also when.

Given the crossover between DFreds and Enhanced Conditions I'm not surprised at this. I'm going to close this issue as I won't be pursuing compatibility between them at this time.

**Closed by eclarke12** 2022-07-28 03:19 UTC
Labels: bug, external, unverified
