### ISSUE TITLE
Won't render two conditions with the same icon.

### ISSUE THREAD

**Issue by strongpauly** [death-save/combat-utility-belt#716] opened 2022-10-08 13:06 UTC
**Describe the bug**
Two conditions can be configured with the same icon, but only one will be rendered.

**To Reproduce**
1. Add two conditions with the same icon to the Condition Lab
2. Select a token
3. Open the Assign Status Effects menu

**Expected behavior**
Both effects should be rendered

**Screenshots**

**Environment Info (please complete the following information):**
 - Foundry Version: v.10.287
 - Game System / Version: dnd5e 2.0.3
 - CUB Version: 1.10.1
 - Browser: Chrome / Electron App
 - OS: OSX

**Additional context**
The solution to this could just be to highlight that this occurs.  It's clear it doesn't necessarily make sense to allow this, but it would be good to show some kind of validation error (it took me a while to track down the specifics of this bug)

**Comment by eclarke12** [comment] 2022-10-08 15:00
Duplicate of #344 
This is one of those long term issues I just haven't gotten around to looking into

**Closed by eclarke12** 2022-10-08 15:00 UTC
Labels: bug, ✨ec, known
