### ISSUE TITLE
Condition Lab Active Effects being saved, when reopened the effect is gone.

### ISSUE THREAD

**Issue by JD-108** [death-save/combat-utility-belt#593] opened 2021-08-29 00:39 UTC
**Describe the bug**
When saving an Active Effect in the Condition Lab the effect will work, but opening the Active Effect for a second time, the effect will no longer be seen.

**To Reproduce**
1. Go to Condition Lab
2. Click on Active Effects
3. Change an active effect to something that works.
4. Click "Submit Changes"
5. Activate Condition on Token
6. Test that Condition works
7. Open the modified Active Effect

**Expected behavior**
The saved Active Effect should remain when I re-open the specific Active Effect

**Environment Info (please complete the following information):**
 - Foundry Version: 0.8.9
 - Game System / Version: dnd5e 1.4.2
 - CUB Version 1.6.1
 - Browser firefox
 - OS Windows 10

**Comment by JD-108** [comment] 2021-08-29 14:02
Update: I have found that saving the Active Effect then closing the Condition Lab will save the effect for future modification. If you click "Save Mapping" then it will undo the change.

**Comment by DuckDungeon** [comment] 2021-08-30 04:10
Came here to report the same, Configure Active Effect does not save. 

Can confirm that JD-108's solution works, but is an odd extra step.

**Comment by eclarke12** [comment] 2021-08-30 04:28
duplicate of #585

**Closed by eclarke12** 2021-08-30 04:28 UTC
Labels: bug, duplicate
