### ISSUE TITLE
Linked condition in chat opens in image view

### ISSUE THREAD

**Issue by benbarbour** [death-save/combat-utility-belt#230] opened 2020-08-07 00:45 UTC
**Describe the bug**
When Enhanced Conditions outputs to chat, clicking on the link opens the journal entry in "image" mode. The user must click "text" in the header bar to view the rules for the condition.

**To Reproduce**
1. Set up Enhanced Conditions to output to chat on the start of each turn
2. Add a condition to a token
3. Start a combat with that token
4. Advance to that token's turn
5. Click on the condition link in the chat message.

**Expected behavior**
The rules for the clicked condition are shown.

**Screenshots**
![image](https://user-images.githubusercontent.com/487715/89596628-91782a00-d80c-11ea-9cb5-f6a6fd339f15.png)

**Environment Info (please complete the following information):**
 - Foundry Version: 0.6.5
 - CUB Version 1.1.3
 - Browser: Foundry App
- OS: Windows 10

**Comment by eclarke12** [comment] 2020-08-07 02:45
This is "working as intended" as that is the built-in Foundry behaviour. This issue on the Foundry issue board suggests a possibility of a toggle for which "side" to show. https://gitlab.com/foundrynet/foundryvtt/-/issues/2559

The alternative is to remove all the images from the journal entries.

Closing for now. May consider removing images if the aforementioned issue is not resolved in the near future.

**Closed by eclarke12** 2020-08-07 02:45 UTC
Labels: bug, external, wontfix
