### ISSUE TITLE
Cannot read property 'hasPlayerOwner' of null on world load in 0.8.6

### ISSUE THREAD

**Issue by Zamrod** [death-save/combat-utility-belt#538] opened 2021-06-07 03:41 UTC
**Describe the bug**
I receive the following error on world load:
triggler.js:74 Uncaught (in promise) TypeError: Cannot read property 'hasPlayerOwner' of null
    at Function._processUpdate (triggler.js:74)
    at Function._onUpdateToken (triggler.js:287)
    at signal.js:136
    at Function._call (eval at <anonymous> (libWrapper-errors.js:249), <anonymous>:4:14)
    at Function.callAll (foundry.js:153)
    at ClientDatabaseBackend.callback (foundry.js:8866)
    at foundry.js:8836
    at Array.map (<anonymous>)
    at ClientDatabaseBackend._handleUpdateEmbeddedDocuments (foundry.js:8836)
    at ClientDatabaseBackend._updateEmbeddedDocuments (foundry.js:8725)

**Environment Info (please complete the following information):**
 - Foundry Version: 0.8.6
 - Game System / Version: dnd5e 1.3.3
 - CUB Version 1.5.0
 - Browser Electron
 - OS Windows 10

**Comment by eclarke12** [comment] 2021-06-07 14:23
duplicate of #534

**Closed by eclarke12** 2021-06-07 14:23 UTC
Labels: bug, duplicate, unverified
