### ISSUE TITLE
Allow Active Effects set on the condition lab to be exported

### ISSUE THREAD

**Issue by SalieriC** [death-save/combat-utility-belt#492] opened 2021-03-08 08:25 UTC
**Is your feature request related to a problem? Please describe.**
When setting up Active Effects in the Condition Lab, these effects do not seem to be exported when the mapping is exported.

**Describe the solution you'd like**
Include Active Effects in the export file to be able to export and import AEs.

**Describe alternatives you've considered**
No Alternative.

**Comment by brunocalado** [comment] 2021-03-09 19:31
please!

**Comment by eclarke12** [comment] 2021-03-12 22:40
duplicate of #429

**Closed by eclarke12** 2021-03-12 22:40 UTC
Labels: enhancement
