### ISSUE TITLE
Updating Triggler doesn't update display name

### ISSUE THREAD

**Issue by Rawrly85** [death-save/combat-utility-belt#150] opened 2020-05-08 13:33 UTC
Steps: 
1. Create. triggler and close the dialog
2. Re-open and change existing triggler
3. Close dialog and re-open, the name is still the one given when first created rather than the new name. 

Names should be re-generated for each edit. 
<img width="684" alt="Screen Shot 2020-05-08 at 6 31 21 AM" src="https://user-images.githubusercontent.com/53245027/81410608-def1d780-90f5-11ea-8dd3-8fd25380efb5.png">

**Comment by eclarke12** [comment] 2020-05-12 19:00
duplicate of #137

**Closed by eclarke12** 2020-05-12 19:00 UTC
