### ISSUE TITLE
Cannot open Active Effect Config on Condition Lab

### ISSUE THREAD

**Issue by Jnnsm** [death-save/combat-utility-belt#526] opened 2021-06-01 00:41 UTC
This pretty much sums it up. I'm running foundry 8.6 and CUB 1.4.
![Screenshot](https://user-images.githubusercontent.com/28005990/120251697-bab0ed80-c258-11eb-964a-6bb8271d02dd.png)

**Comment by eclarke12** [comment] 2021-06-01 02:29
Related to #517. CUB v1.4 is not compatible with Foundry v0.8.x

**Comment by Jnnsm** [comment] 2021-06-01 10:32
Bug is still present on 1.5, but only on custom mapping. On default we can see **this.object.testUserPermission is not a function** error
![Screenshot](https://user-images.githubusercontent.com/28005990/120309078-2e7be600-c2ab-11eb-8be8-6fa5b4015d24.png)

**Comment by davidR1974** [comment] 2021-06-01 13:40
confirmed on 0.8.6 / dnd5 1.3.3

**Comment by davidR1974** [comment] 2021-06-01 18:03
implemented some workaround (not a correction though) regarding that condition lab issue (not able to open the Effect Configureration from the condition lab) :

Step 1 : define one item named "CUB-${conditionname}' for -almost- each condition defined in the condition lab and encode the effect there (all conditions in one effect)
Step 2 : launch macro :

```
let mapsetting = game.settings.get('combat-utility-belt', "activeConditionMap");

mapsetting.forEach(element =>
    {
    element.activeEffect = game.items.getName(`CUB-${element.name}`)?.data.effects.contents[0];
    }
 )

game.settings.set('combat-utility-belt', "activeConditionMap", mapsetting);
```

it seems to work pretty well so far.

**Comment by eclarke12** [comment] 2021-06-03 14:01
I have a fix for this coming in the next update.

**Comment by ctbritt** [comment] 2021-06-10 14:21
Hey there- is there an ETA on the fix, please?

**Comment by ctbritt** [comment] 2021-06-10 14:22
> implemented some workaround (not a correction though) regarding that condition lab issue (not able to open the Effect Configuration from the condition lab) :
> 
> Step 1 : define one item named "CUB-${conditionname}' for -almost- each condition defined in the condition lab and encode the effect there (all conditions in one effect)
> Step 2 : launch macro :
> 
> ```
> let mapsetting = game.settings.get('combat-utility-belt', "activeConditionMap");
> 
> mapsetting.forEach(element =>
>     {
>     element.activeEffect = game.items.getName(`CUB-${element.name}`)?.data.effects.contents[0];
>     }
>  )
> 
> game.settings.set('combat-utility-belt', "activeConditionMap", mapsetting);
> ```
> 
> it seems to work pretty well so far.

So... question: Do you mean create a single item and put ALL the condition effects on that, or an item for each condition row?

**Comment by eclarke12** [comment] 2021-06-14 05:51
> Hey there- is there an ETA on the fix, please?

I had to rewrite it due to the way Foundry handles the Active Effect Config. It seems to be working well and should be ready to go in the next couple of days.

**Comment by soundofyogi** [comment] 2021-06-17 06:32
> implemented some workaround (not a correction though) regarding that condition lab issue (not able to open the Effect Configuration from the condition lab) :
> 
> Step 1 : define one item named "CUB-${conditionname}' for -almost- each condition defined in the condition lab and encode the effect there (all conditions in one effect)
> Step 2 : launch macro :
> 
> ```
> let mapsetting = game.settings.get('combat-utility-belt', "activeConditionMap");
> 
> mapsetting.forEach(element =>
>     {
>     element.activeEffect = game.items.getName(`CUB-${element.name}`)?.data.effects.contents[0];
>     }
>  )
> 
> game.settings.set('combat-utility-belt', "activeConditionMap", mapsetting);
> ```
> 
> it seems to work pretty well so far.

Can you please explain to me step-by-step on how to do this?

**Comment by ctbritt** [comment] 2021-06-17 13:39
I can. Create items with the names of the conditions, i.e., CUB-Blinded, then add a single active effect with all the effects you need, like so: 
![Screen Shot 2021-06-17 at 9 38 49 AM](https://user-images.githubusercontent.com/4516034/122407848-ec5fcf00-cf4f-11eb-8d1c-a6269e0e2d07.png)
and 
![Screen Shot 2021-06-17 at 9 39 18 AM](https://user-images.githubusercontent.com/4516034/122407877-f1bd1980-cf4f-11eb-86c2-ab25fb98886e.png)

**Closed** 2021-06-17 13:45 UTC
Labels: bug, ✨ec

**Comment by soundofyogi** [comment] 2021-06-17 16:30
> I can. Create items with the names of the conditions, i.e., CUB-Blinded, then add a single active effect with all the effects you need, like so:
> ![Screen Shot 2021-06-17 at 9 38 49 AM](https://user-images.githubusercontent.com/4516034/122407848-ec5fcf00-cf4f-11eb-8d1c-a6269e0e2d07.png)
> and
> ![Screen Shot 2021-06-17 at 9 39 18 AM](https://user-images.githubusercontent.com/4516034/122407877-f1bd1980-cf4f-11eb-86c2-ab25fb98886e.png)
> 
> Do this for all the conditions you have. Then run the macro that @davidR1974 posted.

Thank you so much, it's ez to understand
