### ISSUE TITLE
Allow for conditions to link to macros

### ISSUE THREAD

**Issue by NateHawk85** [death-save/combat-utility-belt#254] opened 2020-09-12 13:16 UTC
**Is your feature request related to a problem? Please describe.**
It's not a problem, but it would be nice to be able to run macros upon applying a condition. This would allow CUB to integrate well with Token Magic FX.

**Describe the solution you'd like**
Perhaps another "row" below Journal to link to a specific macro.

**Comment by eclarke12** [comment] 2020-09-14 00:37
duplicate of #110 
please upvote that issue or provide comments there

**Closed by eclarke12** 2020-09-14 00:37 UTC
Labels: enhancement
