### ISSUE TITLE
[BUG] [0.8.7] Can't edit Active Effects for SWADE

### ISSUE THREAD

**Issue by brunocalado** [death-save/combat-utility-belt#549] opened 2021-06-17 14:08 UTC
**Describe the bug** and **To Reproduce**
I click in active effects and it won't work.

**Screenshots**
![image](https://user-images.githubusercontent.com/4999783/122412704-2cc54a00-cf5c-11eb-8735-87cb02925752.png)

**Environment Info (please complete the following information):**
 - Foundry Version: 0.8.7
 - Game System / Version: swade 0.19.4
 - CUB Version 1.5.0
 - Browser chrome
 - OS Windows 10

**Comment by eclarke12** [comment] 2021-06-17 14:19
Duplicate of #526 . fixed in v1.6.0 (coming today)

**Closed by eclarke12** 2021-06-17 14:19 UTC
Labels: bug, duplicate, unverified
