### ISSUE TITLE
Exporting Copies Over Active Effects

### ISSUE THREAD

**Issue by Avitale34** [death-save/combat-utility-belt#437] opened 2020-12-10 22:52 UTC
**Is your feature request related to a problem? Please describe.**
I just made a bunch of flags for active effects using conditions and realized upon exporting that they did not come over. Is that a possible fix in the future?

**Comment by eclarke12** [comment] 2020-12-12 16:44
duplicate of #429

**Closed by eclarke12** 2020-12-12 16:44 UTC
Labels: bug, duplicate
