### ISSUE TITLE
CUB hides buffs from token's status effect menu in PF1

### ISSUE THREAD

**Issue by dmrickey** [death-save/combat-utility-belt#650] opened 2022-01-11 23:39 UTC
**Describe the bug**
From the token menu, Buffs defined on the actor don't show up in the Status Effect options window

**To Reproduce**
1. Go into a pf1 world
2. Have an actor that has buffs defined
3. Have their token on the map
4. Open up the status effects from the token menu -- buffs from the actor won't show up as options
* note that conditions are still shown in the token menu, it's only the buffs defined in the bottom half of the page that are missing while CUB is enabled

**Expected behavior**
Do the above but on step 4 the buffs should show up as options

**Screenshots**
This screenshot is taken with CUB disabled -- The circled Items on the token menu are missing when CUB is enabled.
![image](https://user-images.githubusercontent.com/3664822/149038176-460cef4c-d791-4ac0-9895-1d47ad77106c.png)

**Environment Info (please complete the following information):**
 - Foundry Version: 9 242
 - Game System / Version: pf1 0.80.4
 - CUB Version 1.8.0
 - Browser - foundry's chromium browser
 - OS - Windows 10

**Comment by eclarke12** [comment] 2022-02-01 06:44
As expected pf1e patches `TokenHUD.getStatusEffectChoices` https://gitlab.com/Furyspark/foundryvtt-pathfinder1/-/blame/master/module/canvas.js#L81 which conflicts with CUB's patching of the same method.

Need to come up with a better strategy to deal with duplicate conditions in the HUD

**Comment by eclarke12** [comment] 2022-02-02 06:16
duplicate of #490

**Closed by eclarke12** 2022-02-02 06:16 UTC
Labels: bug, unverified
