### ISSUE TITLE
Actor Name duplicates on character sheet when sheet is interacted with

### ISSUE THREAD

**Issue by senatorhatty** [death-save/combat-utility-belt#715] opened 2022-10-07 14:17 UTC
**Describe the bug**
When I interact with the character sheet in a manner that adds to the sheet or opens a dialog box, the actor's name duplicates itself multiple times across the top of the character sheet

**To Reproduce**
1. Create an actor
2. Open Spells SRD from Compedium
3. Click on Spellbook tab in character sheet
4. Drag any spell from compendium into sheet
5. See error

**Expected behavior**
I expect to not see the name duplicated

**Screenshots**
![image](https://user-images.githubusercontent.com/8930477/194574160-10770897-a355-4d2a-9f4b-5d70517681aa.png)

**Environment Info (please complete the following information):**
 - Foundry Version: [Version 10 Build 287 but I think it existed in older versions]
 - Game System / Version: [dnd5e 2.0.3]
 - CUB Version [e.g. 1.10.1]
 - Browser [Edge, Standalone App]
 - OS [MacOS Monterey 12.6]

**Additional context**
This doesn't appear to break any functionality but it's weird and makes my players not trust Foundry. But it's too bad b/c I am not going back to Fantasy Grounds!

**Comment by eclarke12** [comment] 2022-10-07 14:24
Duplicate of #708

**Closed by eclarke12** 2022-10-07 14:24 UTC
Labels: bug, duplicate, unverified
